name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.5
  image_picker: ^1.1.1
  dio: ^5.2.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  uuid: ^4.5.2

  go_router: ^14.1.4
  pull_to_refresh: ^2.0.0
  english_words: ^4.0.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  flutter_riverpod: ^3.0.1
  stomp_dart_client: ^2.1.3
  web_socket_channel: ^3.0.3
  url_launcher: ^6.1.10
  path_provider: ^2.0.15
  open_file: ^3.2.1
  animations: ^2.0.7

  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.10.0
  app_links: ^6.4.1
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^6.1.0
  network_info_plus: ^7.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_displaymode: ^0.6.0
  firebase_core: ^3.4.1
  firebase_analytics: ^11.3.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1
  package_info_plus: ^8.0.2
  local_auth: ^2.1.7
  mobile_scanner: ^5.2.3
  device_apps: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar_placeholder.png
    - assets/images/building_bg.jpg
